name: Deploy Assets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Validate JSON files
        run: |
          find . -name "*.json" -type f -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            if ! jq . "$file" > /dev/null 2>&1; then
              echo "Invalid JSON: $file"
              exit 1
            fi
          done
      
      - name: Install dependencies for URL check
        run: npm install axios glob

      - name: Validate logo URLs in JSON files
        run: node checkLogos.js

      - name: deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./
